### ISSUE TITLE
Agenda-carousel: scroll driven animation.

### ISSUE THREAD

**Issue by Nazneen05x** [Nazneen05x/S4-S19-Bieb-In-Bloei#23]
### Bron 📚

[scroll-driven-animations.style](https://scroll-driven-animations.style/)
[CSS scroll-driven animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll-driven_animations)
[Scroll-driven animations](https://www.youtube.com/shorts/p8HPqBVp9lI)

------

Met de CSS-eigenschap animation-timeline: view()  kun je  aan de animatie aangeven (doorgeven) om een nieuwe kaart in beeld te laten komen of weer te laten verdwijnen. 

### Animation-timeline: 
De Animation-timeline bepaalt wanneer de animatie gestart of gestopt wordt.

### View() - View(inline)
De view bepaalt de zichtbaarheid van een element: dus wanneer het in beeld komt of weer verdwijnt. 

```css
		/* SCROLL-DRIVEN-ANIMATIONS STYLING */
		@supports (animation-timeline: view()) {
			.card {
				animation-timeline: view(inline);
				animation-name: animate-in-and-out;
			}

			@keyframes animate-in-and-out {
				entry 0% {
					opacity: 0;
					transform: translate(100%);
				}
				entry 100% {
					opacity: 1;
					transform: translateX(0);
				}

				exit 0% {
					opacity: 1;
					transform: translateX(0);
				}
				exit 100% {
					opacity: 0;
					transform: translate(-10%);
				}
			}
		}
	}
  ```
